import { GoverningBody } from '../models/governing-body.model';
import { SPORT_IDS } from './sports.seed';

const now = new Date().toISOString();

export const GOVERNING_BODY_IDS = {
  fifa: 'gb-fifa',
  icc: 'gb-icc',
  fiba: 'gb-fiba',
  itf: 'gb-itf',
  bwf: 'gb-bwf',
  fih: 'gb-fih',
} as const;

export const GOVERNING_BODIES_SEED: GoverningBody[] = [
  {
    id: GOVERNING_BODY_IDS.fifa,
    sportId: SPORT_IDS.football,
    name: 'FIFA',
    description: 'International governing body for football.',
    logo: '',
    emoji: '⚽',
    color: '#2563EB',
    establishedAt: '1904-05-21',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: GOVERNING_BODY_IDS.icc,
    sportId: SPORT_IDS.cricket,
    name: 'ICC',
    description: 'International governing body for cricket.',
    logo: '',
    emoji: '🏏',
    color: '#0EA5E9',
    establishedAt: '1909-06-15',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: GOVERNING_BODY_IDS.fiba,
    sportId: SPORT_IDS.basketball,
    name: 'FIBA',
    description: 'International governing body for basketball.',
    logo: '',
    emoji: '🏀',
    color: '#F97316',
    establishedAt: '1932-06-18',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: GOVERNING_BODY_IDS.itf,
    sportId: SPORT_IDS.tennis,
    name: 'ITF',
    description: 'International governing body for tennis.',
    logo: '',
    emoji: '🎾',
    color: '#22C55E',
    establishedAt: '1913-03-01',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: GOVERNING_BODY_IDS.bwf,
    sportId: SPORT_IDS.badminton,
    name: 'BWF',
    description: 'International governing body for badminton.',
    logo: '',
    emoji: '🏸',
    color: '#A855F7',
    establishedAt: '1934-07-05',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: GOVERNING_BODY_IDS.fih,
    sportId: SPORT_IDS.hockey,
    name: 'FIH',
    description: 'International governing body for hockey.',
    logo: '',
    emoji: '🏑',
    color: '#EF4444',
    establishedAt: '1924-01-07',
    createdAt: now,
    updatedAt: now,
  },
];
