import { Participant } from '../models/participant.model';
import { ORGANISATION_IDS } from './organisations.seed';

const now = new Date().toISOString();

export const PARTICIPANTS_SEED: Participant[] = [
  {
    id: 'participant-1',
    organisationId: ORGANISATION_IDS.premierLeague,
    name: 'Erling Haaland',
    role: 'Forward',
    nationality: 'Norway',
    jerseyNumber: 9,
    avatar: '',
    dateOfBirth: '2000-07-21',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'participant-2',
    organisationId: ORGANISATION_IDS.premierLeague,
    name: 'Bukayo Saka',
    role: 'Winger',
    nationality: 'England',
    jerseyNumber: 7,
    avatar: '',
    dateOfBirth: '2001-09-05',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'participant-3',
    organisationId: ORGANISATION_IDS.ipl,
    name: 'Virat Kohli',
    role: 'Batsman',
    nationality: 'India',
    jerseyNumber: 18,
    avatar: '',
    dateOfBirth: '1988-11-05',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'participant-4',
    organisationId: ORGANISATION_IDS.ipl,
    name: 'Jasprit Bumrah',
    role: 'Bowler',
    nationality: 'India',
    jerseyNumber: 93,
    avatar: '',
    dateOfBirth: '1993-12-06',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'participant-5',
    organisationId: ORGANISATION_IDS.nba,
    name: 'LeBron James',
    role: 'Forward',
    nationality: 'USA',
    jerseyNumber: 23,
    avatar: '',
    dateOfBirth: '1984-12-30',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'participant-6',
    organisationId: ORGANISATION_IDS.nba,
    name: 'Stephen Curry',
    role: 'Guard',
    nationality: 'USA',
    jerseyNumber: 30,
    avatar: '',
    dateOfBirth: '1988-03-14',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'participant-7',
    organisationId: ORGANISATION_IDS.atp,
    name: 'Carlos Alcaraz',
    role: 'Singles Player',
    nationality: 'Spain',
    jerseyNumber: undefined,
    avatar: '',
    dateOfBirth: '2003-05-05',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'participant-8',
    organisationId: ORGANISATION_IDS.atp,
    name: 'Jannik Sinner',
    role: 'Singles Player',
    nationality: 'Italy',
    jerseyNumber: undefined,
    avatar: '',
    dateOfBirth: '2001-08-16',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'participant-9',
    organisationId: ORGANISATION_IDS.bwfWorldTour,
    name: 'Viktor Axelsen',
    role: 'Singles Player',
    nationality: 'Denmark',
    jerseyNumber: undefined,
    avatar: '',
    dateOfBirth: '1994-01-04',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'participant-10',
    organisationId: ORGANISATION_IDS.bwfWorldTour,
    name: 'An Se-young',
    role: 'Singles Player',
    nationality: 'South Korea',
    jerseyNumber: undefined,
    avatar: '',
    dateOfBirth: '2002-02-05',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'participant-11',
    organisationId: ORGANISATION_IDS.fihProLeague,
    name: 'Harmanpreet Singh',
    role: 'Defender',
    nationality: 'India',
    jerseyNumber: 13,
    avatar: '',
    dateOfBirth: '1996-01-06',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'participant-12',
    organisationId: ORGANISATION_IDS.fihProLeague,
    name: 'Thierry Brinkman',
    role: 'Forward',
    nationality: 'Netherlands',
    jerseyNumber: 9,
    avatar: '',
    dateOfBirth: '1995-03-19',
    createdAt: now,
    updatedAt: now,
  },
];
